<!doctype html>
<!-- html file with php statements when needed -->
<html>
<head>
	<title>Christian Chandler FACS code challenge</title>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script src="test.js"></script>
	<link rel="stylesheet" href="reset.css">
	<link rel="stylesheet" href="test.css">
</head>

<body>
<!-- stub controll functions -->
	<div id="cntrBtnGroup">
		<button id="toggleStubs">Stub Controls on/off</button>
		<button id="toggleDelBtn" class="stub">Del Button on/off</button>
		<button id="selectCtrl" class="stub">Select item[0]</button>
	</div>
<!-- END stub controll functions -->

	<div id="container">

<!-- added item container -->
		<div class="container">

			<div id="itemBox" class="facs-box">
				<!-- dynamically place added item elements here -->
<!-- 			<div class="stub facs-item">Item #1</div>    // facs-item-selected
				<div class="stub facs-item">Item #2</div>
				<div class="stub facs-item">Item #3</div>
				<div class="stub facs-item">Item #4</div>
				<div class="stub facs-item">Item #5</div> -->
			</div>

			<button id="addBtn">ADD Item</button>
			<button id="deleteBtn" class="facs-button-disabled">Delete Item</button>

		</div>


<!-- deleted item container -->
		<div class="container">

			<div id="deleteBox" class="facs-box facs-box-disabled">
				<!-- dynamically place deleted item element here -->
			</div>

		</div>

	</div>
</body>

</html>