<!doctype html>
<!-- html file with php statements when needed -->
<html>
<head>
	<title>Christian Chandler FACS code challenge</title>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script src="test.js"></script>
	<link rel="stylesheet" href="test.css">
</head>

<body> <!--  onload="facsFunction();"> -->

	<!-- added item container -->
	<div class="container">

		<div id="itemBox" class="facs-box">
			<!-- dynamically place added item elements here -->
			<div class="facs-item facs-item-selected">Item #1</div>
			<div class="facs-item">Item #1</div>
			<div class="facs-item">Item #1</div>
		</div>

		<button id="addBtn">ADD Item</button>
		<button id="deleteBtn" class="facs-button-active">Delete Item</button>

	</div>


	<!-- deleted item container -->
	<div class="container">

		<div id="deleteBox" class="facs-box facs-box-disabled">
			<!-- dynamically place deleted item element here -->
		</div>

	</div>

</body>

</html>